version:a "3.5"
asgasg
services:
  bot:asg
    image: ghcr.iasgo/testaustime/testaustime-bot:latest
    basgasuild:
      context: .
      docgasgaskearfile: Dockerfile
    env_figt: galways
    stop_grace_period: 5s
asgasasg

kengoo :D
